### ISSUE TITLE
есть идея

### ISSUE THREAD

**Issue by dimontajik** [skypach/skypach.ru#1]
есть скрипт 2 версии этого движка давай займемся?

**Comment by skypach** [comment]
Я видел демо скрипта 2 версии. Чем оно лучше первой? Опять же, дизайн придется переделывать...

Если хочешь помочь, помоги за аудио-плеером разобраться. Чтобы играл не переставая, при переходе по страницам.

**Comment by dimontajik** [comment]
во второй версии это исправленно

**Comment by skypach** [comment]
Во второй версии движка тоже самое. И она вроде была закрыта php шифровальщиком каким-то.
